

list_of_options = [
        ["Steam Locomotive:", "The Introduction", "Imagine this, but in a world where everything is a song", "(Verse 1)\n In a world of rhythm, where the tracks entwine,\n A steam locomotive, a song in every line.\n Propelling itself, with a steamy embrace,\n Burning coal and oil, in a rhythmic chase.\n (Chorus)\n Oh, steam engine on wheels, a melody so grand,\n Expanding steam, like a magic band.\n Pistons dancing, connected to the ride,\n In this symphony of motion, on the steaming tide.\n (Verse 2)\n Fuel ablaze, in the boiler's fiery hold,\n Water and heat, in a tale untold.\n Cylinders sigh, as steam takes its chance,\n A locomotion waltz, in a rhythmic dance.\n (Bridge)\n Variations play in this locomotive song,\n Electric hums, as the turbines throng.\n Fuel and water, in a tender's embrace,\n As the wheels turn, leaving trails of grace.\n"],
        ["Shoes:", "Construction", "in the past, shoes where made from old fruit", "In a historical twist, footwear of the past was crafted from unconventional materials, including repurposed old fruit. The soles, the bottom part of the shoes that make contact with the ground, were ingeniously fashioned from a variety of fruit-based compounds. This unique approach to shoemaking added an element of resourcefulness and sustainability to the art of crafting shoes.\n While contemporary shoes predominantly feature soles made from materials like natural rubber, polyurethane, or polyvinyl chloride (PVC) compounds, the historical practice involved utilizing the versatile properties of fruits. The soles of these shoes could take on simple forms, comprising a single layer of fruit-based material, or showcase complexity with multiple structures and layers, incorporating various fruit-derived compounds."],
        ["Pokemon:", "1996–1998: First generation", "There are actually 150 pokemon", "In the initial generation of games, a total of 150 Pokémon species were introduced (in National Pokédex order, covering Pokémon from Bulbasaur to Mew). These games pioneered fundamental concepts such as capturing, training, battling, and trading Pokémon with both computer and human players. The game's setting is within the fictional Kanto region, although the term 'Kanto' wasn't officially employed until the subsequent second generation."],
        ["Cows:", "Population", "There are more cows in the UK than people", "In the United Kingdom, the number of cows surpasses the human population. The cattle population in Britain experienced a notable increase, rising from 9.8 million in 1878 to 11.7 million in 1908. Interestingly, the surge in beef consumption outpaced this growth. Britain earned the moniker 'stud farm of the world' as it began exporting livestock to nations lacking native cattle breeds. By 1929, a striking 80% of the global meat trade comprised products originating from English breeds. Across the Atlantic, the United States boasted nearly 70 million cattle by the early 1930s."],
        ["Shoes:", "Construction", "in the past, shoes where made from old fruit", "In a historical twist, footwear of the past was crafted from unconventional materials, including repurposed old fruit. The soles, the bottom part of the shoes that make contact with the ground, were ingeniously fashioned from a variety of fruit-based compounds. This unique approach to shoemaking added an element of resourcefulness and sustainability to the art of crafting shoes.\n While contemporary shoes predominantly feature soles made from materials like natural rubber, polyurethane, or polyvinyl chloride (PVC) compounds, the historical practice involved utilizing the versatile properties of fruits. The soles of these shoes could take on simple forms, comprising a single layer of fruit-based material, or showcase complexity with multiple structures and layers, incorporating various fruit-derived compounds."],
        ["Steam Locomotive:", "The Introduction", "Imagine this, but in a world where everything is a song", "(Verse 1)\n In a world of rhythm, where the tracks entwine,\n A steam locomotive, a song in every line.\n Propelling itself, with a steamy embrace,\n Burning coal and oil, in a rhythmic chase.\n (Chorus)\n Oh, steam engine on wheels, a melody so grand,\n Expanding steam, like a magic band.\n Pistons dancing, connected to the ride,\n In this symphony of motion, on the steaming tide.\n (Verse 2)\n Fuel ablaze, in the boiler's fiery hold,\n Water and heat, in a tale untold.\n Cylinders sigh, as steam takes its chance,\n A locomotion waltz, in a rhythmic dance.\n (Bridge)\n Variations play in this locomotive song,\n Electric hums, as the turbines throng.\n Fuel and water, in a tender's embrace,\n As the wheels turn, leaving trails of grace.\n"],
        ["Cruise ship:", "The Introduction", "Cruises were popularised when the Queen Elizabeth went on one in the 1920s", "Cruise ships are large passenger ships used mainly for vacationing. Unlike ocean liners, which are used for transport, cruise ships typically embark on round-trip voyages to various ports of call, where passengers may go on tours known as 'shore excursions.' Cruises were popularized when Queen Elizabeth went on one in the 1920s. This historic voyage by the Queen contributed significantly to the fascination with cruise travel, capturing the public's imagination and making cruises a symbol of luxury and sophistication. On 'cruises to nowhere' or 'nowhere voyages,' some cruise ships make two- to three-night round trips without visiting any ports of call. The enduring allure of cruise vacations can be traced back to this early moment of royal endorsement, establishing a foundation for the industry's widespread popularity."],
        ] 
